version: '3'

services:
  portainer-agent-plane:
    image: portainer/agent
    ports:
      - '9001:9001'
    networks:
      - plane-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

  mavproxy-plane:
    image: uavaustin/mavproxy
    command: --master=/dev/pixhawk
             --out udpin:0.0.0.0:14550
             --out udpin:0.0.0.0:14551
             --daemon
             --nowait
    ports:
      - '14550:14550/udp'
      - '14551:14551/udp'
    networks:
      - plane-net
    devices:
      - /dev/pixhawk:/dev/pixhawk
    restart: unless-stopped

  telemetry-plane:
    image: uavaustin/telemetry
    environment:
      - PLANE_HOST=mavproxy-plane
      - PLANE_PORT=14550
    ports:
      - '5000:5000'
    networks:
      - plane-net
    restart: unless-stopped

  imagery-plane:
    image: uavaustin/imagery
    environment:
      - BACKEND=z-cam-e1
      - TELEMETRY_HOST=telemetry-plane
      - TELEMETRY_PORT=5000
      - CAMERA_HOST=192.168.168.1
      - CAMERA_PORT=80
      - MAX_IMAGES=2048
    ports:
      - '8081:8081'
    networks:
      - plane-net
    volumes:
      - './imagery:/opt/imagery'
    restart: unless-stopped

networks:
  plane-net:
