FROM elixir:1.8-alpine

WORKDIR /test

ENV MIX_ENV=test

# Setting up the package manager.
RUN mix local.hex --force && mix local.rebar --force

COPY interop-proxy/mix.exs .
COPY interop-proxy/coveralls.json .

# Fetching and then compiling our deps first.
RUN mix deps.get && mix deps.compile

COPY interop-proxy .
COPY common/messages lib/messages

RUN mix compile

CMD mix test && MIX_ENV=test mix coveralls.html
