FROM rust:alpine
WORKDIR /test
RUN apk add build-base #'cc' needed for prost in pathfinder-cli
RUN apk add protoc #docker-alpine not supported by prost's built-in compilers
RUN cargo install --git https://github.com/uavaustin/pathfinder-cli.git --branch clap-cli --root .

# ------------------------------------------------------------------------------

FROM node:12-alpine
ENV NODE_ENV=test
WORKDIR /test
COPY --from=0 /test/ .
COPY common/nodejs/package.json src/common/
COPY tanstar/package.json .
RUN npm install
COPY common/messages/interop.proto \
    common/messages/telemetry.proto \
    common/messages/pathfinder.proto \
    src/messages/
RUN npm run build-msg
COPY common/nodejs src/common
COPY tanstar .
CMD npm test
