ARG BASE=node:10-alpine

FROM ${BASE}

ENV NODE_ENV=test

WORKDIR /test

# We need packages to install the net-ping node dependency.
RUN apk --no-cache add \
    make \
    g++ \
    python-dev

COPY common/nodejs/package.json src/common/
COPY pong/package.json .

RUN npm install

COPY common/messages/stats.proto \
    src/messages/

RUN npm run build-msg

COPY common/nodejs src/common
COPY pong .

CMD npm run lint && npm test
