name: Orchestra

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: making pong
              run: |
                make pong