name: Orchestra

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [
                    mavproxy,
                    interop-proxy,
                    telemetry,
                    pong,
                    forward-interop,
                    imagery,
                    image-rec-master,
                    grafana
                ]
        steps:
            - uses: actions/checkout@v2
            - name: Building services
              run: |
                ./ci/script.sh
              env:
                SERVICE: ${{ matrix.service }}